import os
import json
from datetime import datetime
import openai
import requests

from flask import Flask, request, jsonify, render_template
from bs4 import BeautifulSoup
from werkzeug.utils import secure_filename

from util import extract_text_from_pdf, extract_text_from_docx


# ======================
# Flask Setup
# ======================

app = Flask(__name__, template_folder="templates", static_folder="static")

UPLOAD_FOLDER = "uploads"
HISTORY_FILE = "quiz_history.json"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

if not os.path.exists(HISTORY_FILE):
    with open(HISTORY_FILE, "w") as f:
        json.dump([], f)


# ======================
# OpenAI Setup
# ======================

def get_key():
    with open("api key.txt") as f:
        return f.read().strip()

client = openai.OpenAI(api_key=get_key())


# ======================
# Home
# ======================

@app.route("/")
def home():
    return render_template("index.html")


# ======================
# URL text extraction
# ======================

def extract_text_from_url(url):

    try:

        headers = {"User-Agent": "Mozilla/5.0"}

        r = requests.get(url, headers=headers, timeout=10)

        r.raise_for_status()

        soup = BeautifulSoup(r.text, "html.parser")

        for tag in soup(["script", "style", "nav", "footer"]):
            tag.decompose()

        return soup.get_text(separator=" ", strip=True)

    except Exception as e:

        print("URL ERROR:", e)

        return None


# ======================
# Save Quiz History
# ======================

def save_quiz(quiz_data):
    history_file = "quiz_history.json"

    # Fix: Check if file is empty (0 bytes) before loading
    if not os.path.exists(history_file) or os.stat(history_file).st_size == 0:
        with open(history_file, "w") as f:
            json.dump([], f)

    with open(history_file, "r") as f:
        history = json.load(f)

    # Use the data generated by the AI
    quiz_entry = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "questions": quiz_data["questions"]
    }

    history.append(quiz_entry)
    with open(history_file, "w") as f:
        json.dump(history, f, indent=4)


# ======================
# Quiz Generator
# ======================

def create_quiz(text):
    try:
        if len(text) > 50000:
            text = text[:50000]

        prompt = f"""
Generate quiz.

Rules:
- 10 questions
- 4 choices
- include explanation
- return ONLY JSON object

Format:
{{
 "questions":[
   {{
    "question":"text",
    "choices":["A","B","C","D"],
    "answer":0,
    "explanation":"text"
   }}
 ]
}}

Text:
{text}
"""
        # FIX: Add response_format to force pure JSON output
        completion = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"} 
        )

        raw = completion.choices[0].message.content.strip()
        quiz = json.loads(raw)
        save_quiz(quiz)

        return quiz

    except Exception as e:
        print("QUIZ ERROR:", e)
        return {"error": str(e)}


# ======================
# Quiz Route
# ======================

@app.route("/quizgen", methods=["POST"])
def genquiz():
    text = ""
    
    # Check if a file was uploaded
    if 'file' in request.files:
        file = request.files['file']
        if file.filename != '':
            filename = secure_filename(file.filename)
            filepath = os.path.join(UPLOAD_FOLDER, filename)
            file.save(filepath)

            # Use your extraction functions from util.py
            if filename.endswith(".pdf"):
                text = extract_text_from_pdf(filepath)
            elif filename.endswith(".docx"):
                text = extract_text_from_docx(filepath)
            else:
                with open(filepath, 'r', encoding='utf-8') as f:
                    text = f.read()
    
    # Otherwise, check for a link in the form data
    else:
        link = request.form.get("link", "").strip()
        if link:
            text = extract_text_from_url(link)

    if not text:
        return jsonify({"error": "No text content found"}), 400

    # Generate the quiz (Replacing the undefined 'questions_list' variable)
    quiz_data = create_quiz(text)
    
    if "error" in quiz_data:
        return jsonify(quiz_data), 500

    save_quiz(quiz_data)
    return jsonify(quiz_data)

# ======================
# History Route
# ======================

@app.route("/history")
def history():

    try:

        with open(HISTORY_FILE, "r") as f:

            return jsonify(json.load(f))

    except:

        return jsonify([])


@app.route("/notes")
def notes():
    try:
        # FILE MODE
        if "file" in request.files:
            file = request.files["file"]
            filename = secure_filename(file.filename)
            path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(path)
            ext = filename.split(".")[-1].lower()

            if ext == "pdf":
                text = extract_text_from_pdf(path)
            elif ext == "docx":
                text = extract_text_from_docx(path)
            elif ext == "txt":
                with open(path, "r", encoding="utf8") as f:
                    text = f.read()
            else:
                return jsonify({"error": "Unsupported file"})

            prompt = f"Summarize the given text in bullet point form. Notes must be clear, short, and concise. {text}"

            completion = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=4000
            )

            return completion

        # LINK MODE
        data = request.json

        if data.get("link"):
            text = extract_text_from_url(data["link"])
            if not text:
                return jsonify({"error": "Failed to extract link"})

            prompt = f"Summarize the given text in bullet point form. Notes must be clear, short, and concise. {text}"

            completion = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=4000
            )

            return completion

        return jsonify({"error": "Invalid request"})


    except Exception as e:
        return jsonify({"error": str(e)})
    
@app.route("/delete_quiz", methods=["POST"])
def delete_quiz():
    ts = request.json.get("timestamp")
    with open(HISTORY_FILE, "r") as f:
        history = json.load(f)
    
    # Keep everything EXCEPT the one we want to delete
    history = [q for q in history if q.get("timestamp") != ts]
    
    with open(HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=4)
    return jsonify({"status": "success"})

@app.route("/rename_quiz", methods=["POST"])
def rename_quiz():
    data = request.json
    ts = data.get("timestamp")
    new_name = data.get("new_name")
    
    with open(HISTORY_FILE, "r") as f:
        history = json.load(f)
    
    for q in history:
        if q.get("timestamp") == ts:
            q["custom_name"] = new_name
            break
            
    with open(HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=4)
    return jsonify({"status": "success"})

# ======================
# Run
# ======================

if __name__ == "__main__":

    app.run(debug=True)